include(${CMAKE_CURRENT_LIST_DIR}/assimp_install.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/glfw_install.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/glm_install.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/json_install.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/openexr_install.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/uuid_install.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/directxtex_install.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/sdl3_install.cmake)