set(ASSIMP_SOURCE_DIR     ${CMAKE_CURRENT_LIST_DIR}/../assimp)
set(ASSIMP_BINARY_DIR     ${CMAKE_CURRENT_LIST_DIR}/../../Build/assimp)
set(ASSIMP_INSTALL_PREFIX ${CMAKE_CURRENT_LIST_DIR}/../../Install)


message(STATUS ASSIMP_SOURCE_DIR=${ASSIMP_SOURCE_DIR})
message(STATUS ASSIMP_BINARY_DIR=${ASSIMP_BINARY_DIR})
message(STATUS ASSIMP_BINARY_DIR=${ASSIMP_INSTALL_PREFIX})

execute_process(COMMAND 
    ${CMAKE_COMMAND} -S ${ASSIMP_SOURCE_DIR} -B ${ASSIMP_BINARY_DIR} -DCMAKE_INSTALL_PREFIX=${ASSIMP_INSTALL_PREFIX}
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --build ${ASSIMP_BINARY_DIR} --config Release
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --install ${ASSIMP_BINARY_DIR} --config Release
)