set(DIRECTXTEX_SOURCE_DIR     ${CMAKE_CURRENT_LIST_DIR}/../../Lib/DirectXTex)
set(DIRECTXTEX_BINARY_DIR     ${CMAKE_CURRENT_LIST_DIR}/../../build/DirectXTex)
set(DIRECTXTEX_INSTALL_PREFIX ${CMAKE_CURRENT_LIST_DIR}/../../install)

if (NOT EXISTS ${DIRECTXTEX_BINARY_DIR})
    make_directory(${DIRECTXTEX_BINARY_DIR})
endif()

message(STATUS DIRECTXTEX_SOURCE_DIR=${DIRECTXTEX_SOURCE_DIR})
message(STATUS DIRECTXTEX_BINARY_DIR=${DIRECTXTEX_BINARY_DIR})
message(STATUS DIRECTXTEX_BINARY_DIR=${DIRECTXTEX_INSTALL_PREFIX})

execute_process(COMMAND 
    ${CMAKE_COMMAND} -S ${DIRECTXTEX_SOURCE_DIR} -B ${DIRECTXTEX_BINARY_DIR} -DCMAKE_INSTALL_PREFIX=${DIRECTXTEX_INSTALL_PREFIX} 
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --build ${DIRECTXTEX_BINARY_DIR}   --config Debug
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --install ${DIRECTXTEX_BINARY_DIR} --config Debug
)
execute_process(COMMAND 
    ${CMAKE_COMMAND} -E rename ${DIRECTXTEX_INSTALL_PREFIX}/lib/DirectXTex.lib ${DIRECTXTEX_INSTALL_PREFIX}/lib/DirectXTexd.lib 
)

execute_process(COMMAND
    ${CMAKE_COMMAND} --build ${DIRECTXTEX_BINARY_DIR} --config Release
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --install ${DIRECTXTEX_BINARY_DIR} --config Release
)

set(DIRECTXTEX_TARGETS_DEBUG_CMAKE "")
file(READ ${DIRECTXTEX_INSTALL_PREFIX}/share/directxtex/DirectXTex-targets-debug.cmake DIRECTXTEX_TARGETS_DEBUG_CMAKE)
string(REPLACE "DirectXTex.lib" "DirectXTexd.lib" DIRECTXTEX_TARGETS_DEBUG_CMAKE ${DIRECTXTEX_TARGETS_DEBUG_CMAKE})
file(WRITE ${DIRECTXTEX_INSTALL_PREFIX}/share/directxtex/DirectXTex-targets-debug.cmake ${DIRECTXTEX_TARGETS_DEBUG_CMAKE})