set(NLOHMANN_JSON_SOURCE_DIR     ${CMAKE_CURRENT_LIST_DIR}/../nlohmann_json)
set(NLOHMANN_JSON_BINARY_DIR     ${CMAKE_CURRENT_LIST_DIR}/../../Build/nlohmann_json)
set(NLOHMANN_JSON_INSTALL_PREFIX ${CMAKE_CURRENT_LIST_DIR}/../../Install)


message(STATUS NLOHMANN_JSON_SOURCE_DIR=${NLOHMANN_JSON_SOURCE_DIR})
message(STATUS NLOHMANN_JSON_BINARY_DIR=${NLOHMANN_JSON_BINARY_DIR})
message(STATUS NLOHMANN_JSON_BINARY_DIR=${NLOHMANN_JSON_INSTALL_PREFIX})

execute_process(COMMAND 
    ${CMAKE_COMMAND} -S ${NLOHMANN_JSON_SOURCE_DIR} -B ${NLOHMANN_JSON_BINARY_DIR} -DCMAKE_INSTALL_PREFIX=${NLOHMANN_JSON_INSTALL_PREFIX} 
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --build ${NLOHMANN_JSON_BINARY_DIR} --config Release
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --install ${NLOHMANN_JSON_BINARY_DIR} --config Release
)