set(OPENEXR_SOURCE_DIR     ${CMAKE_CURRENT_LIST_DIR}/../openexr)
set(OPENEXR_BINARY_DIR     ${CMAKE_CURRENT_LIST_DIR}/../../Build/openexr)
set(OPENEXR_INSTALL_PREFIX ${CMAKE_CURRENT_LIST_DIR}/../../Install)


message(STATUS OPENEXR_SOURCE_DIR=${OPENEXR_SOURCE_DIR})
message(STATUS OPENEXR_BINARY_DIR=${OPENEXR_BINARY_DIR})
message(STATUS OPENEXR_BINARY_DIR=${OPENEXR_INSTALL_PREFIX})

execute_process(COMMAND 
    ${CMAKE_COMMAND} -S ${OPENEXR_SOURCE_DIR} -B ${OPENEXR_BINARY_DIR} -DCMAKE_INSTALL_PREFIX=${OPENEXR_INSTALL_PREFIX} 
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --build ${OPENEXR_BINARY_DIR} --config Release
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --install ${OPENEXR_BINARY_DIR} --config Release
)