set(TINYOBJLOADER_SOURCE_DIR     ${CMAKE_CURRENT_LIST_DIR}/../../Lib/tinyobjloader)
set(TINYOBJLOADER_BINARY_DIR     ${CMAKE_CURRENT_LIST_DIR}/../../Build/tinyobjloader)
set(TINYOBJLOADER_INSTALL_PREFIX ${CMAKE_CURRENT_LIST_DIR}/../../Install)


message(STATUS TINYOBJLOADER_SOURCE_DIR=${TINYOBJLOADER_SOURCE_DIR})
message(STATUS TINYOBJLOADER_BINARY_DIR=${TINYOBJLOADER_BINARY_DIR})
message(STATUS TINYOBJLOADER_BINARY_DIR=${TINYOBJLOADER_INSTALL_PREFIX})

execute_process(COMMAND 
    ${CMAKE_COMMAND} -S ${TINYOBJLOADER_SOURCE_DIR} -B ${TINYOBJLOADER_BINARY_DIR} -DCMAKE_INSTALL_PREFIX=${TINYOBJLOADER_INSTALL_PREFIX}
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --build ${TINYOBJLOADER_BINARY_DIR} --config Release
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --install ${TINYOBJLOADER_BINARY_DIR} --config Release
)