set(UUID_SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}/../../Lib/stduuid)
set(UUID_BINARY_DIR ${CMAKE_CURRENT_LIST_DIR}/../../Build/stduuid)
set(UUID_INSTALL_PREFIX ${CMAKE_CURRENT_LIST_DIR}/../../Install)


message(STATUS UUID_SOURCE_DIR=${UUID_SOURCE_DIR})
message(STATUS UUID_BINARY_DIR=${UUID_BINARY_DIR})
message(STATUS UUID_INSTALL_PREFIX=${UUID_INSTALL_PREFIX})

execute_process(COMMAND 
    ${CMAKE_COMMAND} -S ${UUID_SOURCE_DIR} -B ${UUID_BINARY_DIR} -DCMAKE_INSTALL_PREFIX=${UUID_INSTALL_PREFIX}
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --build ${UUID_BINARY_DIR} --config Release
)
execute_process(COMMAND
    ${CMAKE_COMMAND} --install ${UUID_BINARY_DIR} --config Release
)